name: unluac Nightly Build
on:
  push:
  workflow_dispatch:

jobs:
  jarbuild:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17' # JDK 9 слишком древняя, используй 17
        distribution: 'temurin'
        
    - name: Build
      run: |
        mkdir build
        javac -d build -sourcepath src src/unluac/*.java
        # Создаем jar
        jar -cfm build/unluac.jar src/META-INF/MANIFEST.MF -C build .
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: unluac-build
        path: build/unluac.jar
